// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: protos/report.proto

package dec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner     string `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	EventType string `protobuf:"bytes,2,opt,name=EventType,proto3" json:"EventType,omitempty"`
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_report_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_report_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_protos_report_proto_rawDescGZIP(), []int{0}
}

func (x *ReportRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ReportRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

type ReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_report_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_report_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_protos_report_proto_rawDescGZIP(), []int{1}
}

type GetEventFlowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner string `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
}

func (x *GetEventFlowRequest) Reset() {
	*x = GetEventFlowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_report_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventFlowRequest) ProtoMessage() {}

func (x *GetEventFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_report_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventFlowRequest.ProtoReflect.Descriptor instead.
func (*GetEventFlowRequest) Descriptor() ([]byte, []int) {
	return file_protos_report_proto_rawDescGZIP(), []int{2}
}

func (x *GetEventFlowRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type GetEventFlowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventFlowList []*EventFlow `protobuf:"bytes,1,rep,name=EventFlowList,proto3" json:"EventFlowList,omitempty"`
}

func (x *GetEventFlowResponse) Reset() {
	*x = GetEventFlowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_report_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventFlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventFlowResponse) ProtoMessage() {}

func (x *GetEventFlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_report_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventFlowResponse.ProtoReflect.Descriptor instead.
func (*GetEventFlowResponse) Descriptor() ([]byte, []int) {
	return file_protos_report_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventFlowResponse) GetEventFlowList() []*EventFlow {
	if x != nil {
		return x.EventFlowList
	}
	return nil
}

type EventFlow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType     string `protobuf:"bytes,1,opt,name=EventType,proto3" json:"EventType,omitempty"`
	TimestampNano int64  `protobuf:"varint,2,opt,name=TimestampNano,proto3" json:"TimestampNano,omitempty"`
}

func (x *EventFlow) Reset() {
	*x = EventFlow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_report_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFlow) ProtoMessage() {}

func (x *EventFlow) ProtoReflect() protoreflect.Message {
	mi := &file_protos_report_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFlow.ProtoReflect.Descriptor instead.
func (*EventFlow) Descriptor() ([]byte, []int) {
	return file_protos_report_proto_rawDescGZIP(), []int{4}
}

func (x *EventFlow) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventFlow) GetTimestampNano() int64 {
	if x != nil {
		return x.TimestampNano
	}
	return 0
}

type GetEventStatisticsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Samples int64 `protobuf:"varint,1,opt,name=Samples,proto3" json:"Samples,omitempty"`
}

func (x *GetEventStatisticsRequest) Reset() {
	*x = GetEventStatisticsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_report_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventStatisticsRequest) ProtoMessage() {}

func (x *GetEventStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_report_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetEventStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_protos_report_proto_rawDescGZIP(), []int{5}
}

func (x *GetEventStatisticsRequest) GetSamples() int64 {
	if x != nil {
		return x.Samples
	}
	return 0
}

type GetEventStatisticsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventStatisticList []*EventStatistic `protobuf:"bytes,1,rep,name=EventStatisticList,proto3" json:"EventStatisticList,omitempty"`
}

func (x *GetEventStatisticsResponse) Reset() {
	*x = GetEventStatisticsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_report_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventStatisticsResponse) ProtoMessage() {}

func (x *GetEventStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_report_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetEventStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_protos_report_proto_rawDescGZIP(), []int{6}
}

func (x *GetEventStatisticsResponse) GetEventStatisticList() []*EventStatistic {
	if x != nil {
		return x.EventStatisticList
	}
	return nil
}

type EventStatistic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType   string `protobuf:"bytes,1,opt,name=EventType,proto3" json:"EventType,omitempty"`
	SumTimeNano int64  `protobuf:"varint,2,opt,name=SumTimeNano,proto3" json:"SumTimeNano,omitempty"`
	Count       int64  `protobuf:"varint,3,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (x *EventStatistic) Reset() {
	*x = EventStatistic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_report_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventStatistic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStatistic) ProtoMessage() {}

func (x *EventStatistic) ProtoReflect() protoreflect.Message {
	mi := &file_protos_report_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStatistic.ProtoReflect.Descriptor instead.
func (*EventStatistic) Descriptor() ([]byte, []int) {
	return file_protos_report_proto_rawDescGZIP(), []int{7}
}

func (x *EventStatistic) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventStatistic) GetSumTimeNano() int64 {
	if x != nil {
		return x.SumTimeNano
	}
	return 0
}

func (x *EventStatistic) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_protos_report_proto protoreflect.FileDescriptor

var file_protos_report_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x64, 0x65, 0x63, 0x22, 0x43, 0x0a, 0x0d, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x10, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x2b, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x6c, 0x6f,
	0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x4c,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x46,
	0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x64, 0x65, 0x63, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x0d, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x4f, 0x0a, 0x09,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x4e, 0x61, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4e, 0x61, 0x6e, 0x6f, 0x22, 0x35, 0x0a,
	0x19, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x53, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x73, 0x22, 0x61, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x43, 0x0a, 0x12, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x64, 0x65, 0x63, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x52, 0x12, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x66, 0x0a, 0x0e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x75, 0x6d, 0x54, 0x69,
	0x6d, 0x65, 0x4e, 0x61, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x53, 0x75,
	0x6d, 0x54, 0x69, 0x6d, 0x65, 0x4e, 0x61, 0x6e, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x32,
	0xe1, 0x01, 0x0a, 0x0a, 0x44, 0x65, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33,
	0x0a, 0x06, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x2e, 0x64, 0x65, 0x63, 0x2e, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x64,
	0x65, 0x63, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x46,
	0x6c, 0x6f, 0x77, 0x12, 0x18, 0x2e, 0x64, 0x65, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x64, 0x65, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x6c, 0x6f, 0x77,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x12, 0x1e, 0x2e, 0x64, 0x65, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x64, 0x65, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6c, 0x61, 0x74, 0x69, 0x66, 0x72, 0x6f, 0x6e, 0x73, 0x2f, 0x64, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x2d, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2d, 0x63, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x62, 0x67, 0x6f, 0x2f, 0x64, 0x65, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_report_proto_rawDescOnce sync.Once
	file_protos_report_proto_rawDescData = file_protos_report_proto_rawDesc
)

func file_protos_report_proto_rawDescGZIP() []byte {
	file_protos_report_proto_rawDescOnce.Do(func() {
		file_protos_report_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_report_proto_rawDescData)
	})
	return file_protos_report_proto_rawDescData
}

var file_protos_report_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protos_report_proto_goTypes = []any{
	(*ReportRequest)(nil),              // 0: dec.ReportRequest
	(*ReportResponse)(nil),             // 1: dec.ReportResponse
	(*GetEventFlowRequest)(nil),        // 2: dec.GetEventFlowRequest
	(*GetEventFlowResponse)(nil),       // 3: dec.GetEventFlowResponse
	(*EventFlow)(nil),                  // 4: dec.EventFlow
	(*GetEventStatisticsRequest)(nil),  // 5: dec.GetEventStatisticsRequest
	(*GetEventStatisticsResponse)(nil), // 6: dec.GetEventStatisticsResponse
	(*EventStatistic)(nil),             // 7: dec.EventStatistic
}
var file_protos_report_proto_depIdxs = []int32{
	4, // 0: dec.GetEventFlowResponse.EventFlowList:type_name -> dec.EventFlow
	7, // 1: dec.GetEventStatisticsResponse.EventStatisticList:type_name -> dec.EventStatistic
	0, // 2: dec.DecService.Report:input_type -> dec.ReportRequest
	2, // 3: dec.DecService.GetEventFlow:input_type -> dec.GetEventFlowRequest
	5, // 4: dec.DecService.GetEventStatistics:input_type -> dec.GetEventStatisticsRequest
	1, // 5: dec.DecService.Report:output_type -> dec.ReportResponse
	3, // 6: dec.DecService.GetEventFlow:output_type -> dec.GetEventFlowResponse
	6, // 7: dec.DecService.GetEventStatistics:output_type -> dec.GetEventStatisticsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_report_proto_init() }
func file_protos_report_proto_init() {
	if File_protos_report_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_report_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_report_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_report_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetEventFlowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_report_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetEventFlowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_report_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*EventFlow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_report_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetEventStatisticsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_report_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetEventStatisticsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_report_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*EventStatistic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_report_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_report_proto_goTypes,
		DependencyIndexes: file_protos_report_proto_depIdxs,
		MessageInfos:      file_protos_report_proto_msgTypes,
	}.Build()
	File_protos_report_proto = out.File
	file_protos_report_proto_rawDesc = nil
	file_protos_report_proto_goTypes = nil
	file_protos_report_proto_depIdxs = nil
}
